### PR TITLE
fix: language name dropdown

### LINKED ISSUE #222: Drag and drop functionality for Excel file (.xlsx) on landing page is not working
### Issue
- When trying to drag and drop an Excel file (`.xlsx`), the file upload is not working:
Screen Shot 2021-01-23 at 2 18 14 PM

```
event.js:510 Uncaught TypeError: this._drop is not a function
    at Object.handleEvent (event.js:510)
handleEvent @ event.js:510
link-storage-to-kmp.ts:12 Uncaught (in promise) Error: Could not fetch the package info; Did you update the package BCP-47 tag?
    at link-storage-to-kmp.ts:12
    at tslib.es6.js:100
    at Object.throw (tslib.es6.js:81)
    at s (tslib.es6.js:72)
(anonymous) @ link-storage-to-kmp.ts:12
(anonymous) @ tslib.es6.js:100
(anonymous) @ tslib.es6.js:81
s @ tslib.es6.js:72
Promise.then (async)
u @ tslib.es6.js:73
a @ tslib.es6.js:71
Promise.then (async)
u @ tslib.es6.js:73
(anonymous) @ tslib.es6.js:74
__awaiter @ tslib.es6.js:70
e.generateKMPFromStorage @ predictive-text-studio-worker-impl.ts:65
(anonymous) @ predictive-text-studio-worker-impl.ts:87
(anonymous) @ tslib.es6.js:100
(anonymous) @ tslib.es6.js:81
a @ tslib.es6.js:71
Promise.then (async)
u @ tslib.es6.js:73
a @ tslib.es6.js:71
Promise.then (async)
u @ tslib.es6.js:73
a @ tslib.es6.js:71
Promise.then (async)
u @ tslib.es6.js:73
(anonymous) @ tslib.es6.js:74
__awaiter @ tslib.es6.js:70
e.addDictionarySourceToProject @ predictive-text-studio-worker-impl.ts:83
r @ comlink.mjs:94
```
- The Excel file used to test the functionality: `wordlist.xlsx`
Screen Shot 2021-01-23 at 2 20 00 PM

### Note
- The app doesn't have any indication of success/failure

### PR DESCRIPTION
**Pull request by eddieantonio**
The language name dropdown (used to be called `Autocomplete`) was super buggy. Since an autocomplete component is complicated and already exists, I added a depenedency to replace our current one.

This *might* fix #222

### CODE REVIEW

**Comment by eddieantonio** [comment]
Nevermind, haha! This one will require a little more work!

File: src/app/components/LanguageNameInput.svelte [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+  import type { KeyboardMetadata } from "@common/types";
+
+  export let label = "";
+  export let subtext = "";
+  export let bold: boolean = true;
+  export let cyData = "autocomplete-label";
+
+  // To store selected language
+  // TODO: rename to selectedLanguage
+  export let selected: KeyboardMetadata | undefined = undefined;
```
Comment (yehee) [inline src/app/components/LanguageNameInput.svelte:15]: Could this be something that can be taken care of from this PR?

File: rollup.config.js [hunk 2]
```diff
@@ -37,8 +37,8 @@ export const appConfiguration = {
     }),
 
     svelte({
-      dev: !production,
       preprocess: sveltePreprocess(),
+      emitCss: false,
```
Comment (yehee) [inline rollup.config.js:41]: Curious as to what this flag does?

File: src/app/pages/LandingPage.svelte [hunk 3]
```diff
@@ -28,8 +28,13 @@
     continueReady = languageStatus && downloadURL !== "";
   }
 
-  function updateLanguageStatus(event: CustomEvent) {
+  // TODO: rename function; it does more than update language status
+  function setLanguage(event: CustomEvent) {
```
Comment (yehee) [inline src/app/pages/LandingPage.svelte:32]: Could this be something that can be taken care of in this PR?

**Review by yehee — APPROVED** [review]
Looks good to me! Just a few questions I'm personally curious about the PR.

File: src/app/components/LanguageNameInput.svelte (hunk 1 above)
Comment (eddieantonio) [reply src/app/components/LanguageNameInput.svelte:15]: Yes! Honestly, I just forgot >.<

File: rollup.config.js (hunk 2 above)
Comment (eddieantonio) [reply rollup.config.js:41]: It's documented here: https://github.com/sveltejs/rollup-plugin-svelte#extracting-css

However, the build was failing because Rollup expected yet _another_ plugin to process the CSS. We have no such plugin, so I disabled this option!

File: src/app/pages/LandingPage.svelte (hunk 3 above)
Comment (eddieantonio) [reply src/app/pages/LandingPage.svelte:32]: Yes, haha! I'll need to do another refactoring pass in a new PR.
