### PR TITLE
[#158] feat: disable button on landing page

### LINKED ISSUE #158: Fix: disable button on landing page
# Background 
Currently the link shows a disable cursor on hover but user is still able to click on the link to download an unexpected file. 

## Fix 
- [x] Disable the click functionally to avoid user from downloading this unexpected file by accident

### PR DESCRIPTION
**Pull request by IanSeng**
# Summary 
Discovered a bug of the current disable issue when I am working on my task so I pull in this quick pr to fix it. This pr is to fix the **disabling bug** for the **download link** on the landing page. Instead of just showing a disabled cursor, now it will also disable user to click on the link and show disable cursor at the same time. 

# Issue 
#158

### CODE REVIEW

File: src/app/components/DownloadKMP.svelte [hunk 1]
```diff
@@ -3,25 +3,32 @@
...
+  <a
+    href={downloadURL ? downloadURL : '#'}
+    download="Example.kmp"
+    class="download-component__link"
+    class:download-component__link--disabled={downloadURL == ''}
+    data-cy="download-kmp"
+    data-download-state={downloadURL ? 'ready' : 'disabled'}>
+    Download KMP Package
+  </a>
+</div>
```
Comment (eddieantonio) [inline src/app/components/DownloadKMP.svelte:34]: Is the wrapper `<div>` necessary? Why?

Comment (IanSeng) [reply src/app/components/DownloadKMP.svelte:34]: Yup, the wrapper `<div>` is to inherit the style of `cursor: not-allowed;` while the `<a>` will only responsible for `pointer-events: none`. Since if `cursor: not-allowed;` & `pointer-events: none` exist together as a style for a single tag, only one of them will be selected, depending on the order. This was the reason why before the fix it will only show disabled cursor but the user is still able to click on the `<a>` tag.  

The behaviour now will be the wrapper class `<div>` giving the style of `cursor: not-allowed;` and the `<a>` tag being refrained from clicking by `pointer-events: none;`

Comment (eddieantonio) [reply src/app/components/DownloadKMP.svelte:34]: Oh wow! Yeah, if the `<a>` gets `pointer-events: none` it can't get... pointer events... including the event that changes the cursor!

**Review by eddieantonio — APPROVED** [review]
LGTM!

I learned something new abount `pointer-events: none`!
