### PR TITLE
fix the bug in drag and drop component

### LINKED ISSUE #149: Fix the bug for the drag and drop functionality
When drop a file to the website, it will download the file instead of uploading to the database >.<

### PR DESCRIPTION
**Pull request by xqiu1**
Fixes #149

### CODE REVIEW

File: src/app/components/Upload.svelte [hunk 1]
```diff
@@ -52,6 +51,10 @@
     dragEnterCounter--;
   };
 
+  const handleDragOver = () => {
+    dragEnterCounter = 0;
+  };
+
```
Comment (xqiu1) [inline src/app/components/Upload.svelte:57]: Without listening to dragover event, we will not able to call handleDrop() 😔

**Review by eddieantonio — APPROVED** [review]
LGTM!

**Review by IanSeng — APPROVED** [review]
LGTM too!
