### PR TITLE
[#75] Add in interfaces for kmp jsson file

### LINKED ISSUE #75: Update to actual kmp.json format 😫
I was wrong about the format of a `kmp.json` file. It actually follows this spec: 

Documentation: https://help.keyman.com/developer/11.0/reference/file-types/metadata
(Outdated) Documentation: https://github.com/keymanapp/keyman/wiki/KMP-Metadata-File-(kmp.inf-and-kmp.json)#fields
JSON Schema: https://api.keyman.com/schemas/package.json

Here are some example `kmp.json` files to get you started:

This one is from https://downloads.keyman.com/models/nrc.en.mtnt/0.1.4/nrc.en.mtnt.model.kmp:

```json
{
  "system": {
    "keymanDeveloperVersion": "12.0.1500.0",
    "fileVersion": "12.0"
  },
  "options": {
    "followKeyboardVersion": false
  },
  "info": {
    "author": {
      "description": "Eddie Antonio Santos",
      "url": "mailto:Eddie.Santos@nrc-cnrc.gc.ca"
    },
    "copyright": {
      "description": "© 2019 National Research Council Canada"
    },
    "name": {
      "description": "English language model mined from MTNT"
    },
    "version": {
      "description": "0.1.4"
    }
  },
  "files": [
    {
      "name": "nrc.en.mtnt.model.js",
      "description": "Lexical model nrc.en.mtnt.model.js",
      "copyLocation": "0",
      "fileType": ".model.js"
    }
  ],
  "lexicalModels": [
    {
      "name": "English dictionary (MTNT)",
      "id": "nrc.en.mtnt",
      "languages": [
        {
          "name": "English",
          "id": "en"
        },
        {
          "name": "English (US)",
          "id": "en-us"
        },
        {
          "name": "English (Canada)",
          "id": "en-ca"
        }
      ]
    }
  ]
}
```

This one is from https://downloads.keyman.com/models/nrc.str.sencoten/1.0.5/nrc.str.sencoten.model.kmp

```json
{
  "system": {
    "keymanDeveloperVersion": "12.0.1500.0",
    "fileVersion": "12.0"
  },
  "options": {
    "followKeyboardVersion": false
  },
  "info": {
    "author": {
      "description": "Eddie Antonio Santos",
      "url": "mailto:Eddie.Santos@nrc-cnrc.gc.ca"
    },
    "copyright": {
      "description": "© 2019 Timothy Montler and the W̱SÁNEĆ School Board"
    },
    "name": {
      "description": "SENĆOŦEN (Saanich Dialect) Lexical Model"
    },
    "version": {
      "description": "1.0.5"
    }
  },
  "files": [
    {
      "name": "nrc.str.sencoten.model.js",
      "description": "Lexical model nrc.str.sencoten.model.js",
      "copyLocation": "0",
      "fileType": ".model.js"
    }
  ],
  "lexicalModels": [
    {
      "name": "SENĆOŦEN dictionary",
      "id": "nrc.str.sencoten",
      "languages": [
        {
          "name": "North Straits Salish",
          "id": "str"
        },
        {
          "name": "SENĆOŦEN",
          "id": "str-Latn"
        }
      ]
    }
  ]
}
```

---

**NOTE**: this does _not_ invalidate #72 or #51! Those are still useful. The `.model_info` files are still used for **public** distribution of Keyman lexical models. I mistakenly assumed that the `kmp.json` and `.model_info` files were the same 😩

### PR DESCRIPTION
**Pull request by jienius**
Fixes #75

### CODE REVIEW

File: src/common/model-info-file.ts [hunk 1]
```diff
@@ -1,36 +1,37 @@
...
+interface ModelInfoFileLink {
   name: string;
   url: string;
 }
 
-export interface ModelRelatedInfo {
-  deprecates?: boolean;
-  deprecatedBy?: boolean;
+interface ModelInfoFileRelated {
+  deprecates?: string;
```
Comment (eddieantonio) [inline src/common/model-info-file.ts:34]: Really love it that the official docs directly contradict this 💀 💀 💀

File: src/worker/generate-kmp-json.ts [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+  keymanDeveloperVersion: string,
+  fileVersion: string,
+  followKeyboardVersion: boolean
+): string {
+  const system: KmpJsonFileSystem = { keymanDeveloperVersion, fileVersion };
+  const options: KmpJsonFileOptions = { followKeyboardVersion };
+  const kmpJson: KmpJsonFile = { system, options };
+
+  return JSON.stringify(kmpJson);
+}
```
Comment (eddieantonio) [inline src/worker/generate-kmp-json.ts:20]: Honestly, I don't really find the value in this function, especially since it doesn't allow you to specify the lexical model — which is the most important part for our purposes!

I won't request changes for this PR, but if I did, I'd suggest just omitting this function and its test! 😂

File: src/common/model-info-file.ts [hunk 3]
```diff
@@ -1,36 +1,37 @@
 /**
  * Interfaces derived from the keyman documentation: https://help.keyman.com/developer/cloud/model_info/1.0/
+ * Modified from: https://github.com/keymanapp/keyman/blob/master/developer/js/source/lexical-model-compiler/model-info-file.ts
```
Comment (eddieantonio) [inline src/common/model-info-file.ts:3]: Excellent citations!

File: src/common/kmp-json-file.ts [hunk 4]
```diff
@@ -0,0 +1,82 @@
+/**
+ * Interfaces derived from the keyman documentation: https://help.keyman.com/developer/11.0/reference/file-types/metadata
+ * Copied from: https://github.com/keymanapp/keyman/blob/master/developer/js/source/lexical-model-compiler/model-info-file.ts
```
Comment (eddieantonio) [inline src/common/kmp-json-file.ts:3]: Excellent citations!

**Review by eddieantonio — APPROVED** [review]
LGTM! Thanks for doing this!

I want to build upon this work, so I'm gonna merge it right away! 👍
